using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace Stridell_Origins.Services.SupabaseModels
{
    [Table("games")]
    public class SupaGames:BaseModel
    {
        [PrimaryKey("game_id", false)] // false indicates it's auto-generated by the DB (SERIAL)
        public int GameId { get; set; }

        [Column("game_name")]
        public string GameName { get; set; } = string.Empty;

        [Column("developer")]
        public string? Developer { get; set; }

        [Column("publisher")]
        public string? Publisher { get; set; }

        [Column("genre")]
        public string? Genre { get; set; }

        [Column("release_date")]
        public DateTime? ReleaseDate { get; set; }

        [Column("price")]
        public decimal Price { get; set; }

        [Column("stock_quantity")]
        public int StockQuantity { get; set; }

        [Column("description")]
        public string? Description { get; set; }

        [Column("system_requirements")]
        public string? SystemRequirements { get; set; }

        [Column("rating")]
        public decimal? Rating { get; set; }

        [Column("language")]
        public string? Language { get; set; }

        [Column("image_url")]
        public string? ImageUrl { get; set; }

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

        [Column("is_available")]
        public bool IsAvailable { get; set; }
    }
}

